Vagrant.configure("2") do |config|
  config.vm.box = "darrenpmeyer/ubuntu-xenial64-mini"
  config.vm.box_version = "0.2.0"
  config.vm.hostname = "vagrant-xenial64-xubuntu"
  config.vm.provision "shell", inline: "bash /vagrant/provision.sh"  

  config.vm.provider "vmware_fusion" do |v, override|
    v.vmx["memsize"] = "3072"
    v.gui = true
  end
end
