Vagrant.configure("2") do |config|
  # config.vm.box = "darrenpmeyer/ubuntu-xenial64-mini"
  config.vm.box = "darrenpmeyer/ubuntu-xenial64-mini"
  config.vm.box_version = "0.2.0"
  config.vm.hostname = "vagrant-xenial64-xubuntu"
  config.vm.provision "shell", inline: "bash /vagrant/provision.sh"  
  # config.vm.provision "shell", inline: "bash /vagrant/vagrant/install-eclipse.sh"

  config.vm.provider "vmware_fusion" do |v, override|
    # override.vm.box_url = "https://s3.us-east-2.amazonaws.com/research-vagrant-boxes/basebox.box"
    v.vmx["memsize"] = "3072"
    v.gui = true
  end
end
